apiVersion: helm.gmsops.io/v1beta1
kind: App
metadata:
  namespace: ${{values.app}}
  name: ${{values.app}}
spec:
  compositionRef:
    name: apps-composition
  parameters:
    name: ${{values.app}}
    image: ${{values.registry}}/${{values.project}}/${{values.app}}
    tag: v0.0.1
    port: "${{values.port}}"
    hostname: ${{values.hostProduction}}
    {% if not values.s3 %}
    s3: false
    {% endif %}
    {% if not values.rds %}
    rds: false
    {% endif %}
