apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app}}-component
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: GMSOPS/${{values.app}}
    backstage.io/kubernetes-namespace: backstage
spec:
  type: service
  lifecycle: production
  owner: devops
  system: demo
  providesApis:
    - ${{values.app}}-component-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.app}}-component-api
  description: Hello World example for RESTAPI
spec:
  type: openapi
  lifecycle: production
  system: demo
  owner: devops
  providesApis:
    - storage.gms-ops.io/v1
  definition: 
    $text: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml
