apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.project}}-workflows
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "argo-workflows"
    server: https://kubernetes.default.svc
  project: ${{values.project}}-workflows
  source:
    path: "./crossplane/workflows"
    repoURL: ${{values.repoUrl}}
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
