apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: common-apps-${{values.project}}-production
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: ${{values.project}}-production
  source:
    path: "./argocd/production/common"
    repoURL: ${{values.repoUrl}}
    targetRevision: "main"
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - "CreateNamespace=true"