# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: ${{values.project}}-production
#   namespace: argo-cd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   destination:
#     namespace: "${{values.project}}"
#     server: ${{values.productionApiServerUrl}}
#   project: ${{values.project}}-production
#   source:
#     path: "./crossplane/production"
#     repoURL: ${{values.repoUrl}}
#     targetRevision: main
#     directory:
#       recurse: true
#   syncPolicy:
#     automated:
#       prune: false
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
