argo-apps:
  spec:
    destination:
      server: "${{values.productionApiServerUrl}}"
    project: "${{values.app}}-production"
    suffix: "production"

  apps:
    ${{values.app}}:
      ns: ${{values.app}}
      source:
        url: "${{values.repoUrl}}"
        branch: "main"
      path: ./crossplane/production
      autoSync: true


