apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: devops
  description: DevOps

  links:
    - url: http://www.devxp-tech.io/
      title: Website
    - url: https://devxp-tech.local/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: GMSOPS
    email: info@gms-ops.net
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [group:engineering]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: engineering
  description: Enjenir

  links:
    - url: http://www.devxp-tech.io/
      title: Website
    - url: https://devxp-tech.local/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: GMSOPS-Enjenir
    email: info@gms-ops.net
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: baja-ks
spec:
  profile:
    displayName: Baja-KS
    email: lukic.l210@gmail.com
    picture: https://i.kym-cdn.com/entries/icons/original/000/032/379/Screen_Shot_2020-01-09_at_2.22.56_PM.png
  memberOf: [gmsops, employees]
# ---
# apiVersion: backstage.io/v1alpha1
# kind: Location
# metadata:
#   name: teams
#   description: A collection of all Backstage example Groups
# spec:
#   targets:
#     - ./engineering.yaml
#     - ./dev.yaml
#     - ./ops.yaml
#     - ./dba.yaml
