argo-apps:
  spec:
    destination:
      server: "${{values.developmentApiServerUrl}}"
    project: "${{values.app}}-development"
    suffix: "development"

  apps:
    ${{values.app}}:
      ns: ${{values.app}}
      source:
        url: "${{values.repoUrl}}"
        branch: "main"
      path: ./crossplane/development
      autoSync: true


