apiVersion: helm.gmsops.io/v1beta1
kind: App
metadata:
  namespace: ${{values.app}}
  name: ${{values.app}}
spec:
  compositionRef:
    name: apps-composition
  parameters:
    name: ${{values.app}}
    image: ${{values.registry}}/${{values.project}}/${{values.app}}
    tag: v0.0.1
    port: "${{values.port}}"
    hostname: ${{values.hostStaging}}
    ${{ "s3: false" if values.s3 == false -}}
    ${{ "rds: false" if values.rds == false -}}
