apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: bucket-template
  title: S3 Bucket Template
  description: Create a S3 Bucket on AWS

  tags:
    - aws
    - s3
    - infrastructure
    - bucket
    - resource
spec:
  owner: group:sre-team
  type: resource

  parameters:
    - title: Provide some simple information
      required:
        - project
        - app
        - environment
        - region
      properties:
        project:
          title: Project Name
          type: string
          description: Unique name of the project
          enum:
            - demo
        app:
          title: Application Name
          type: string
          description: Unique name of the application
          ui:field: EntityNamePicker
        environment:
          title: Environment
          type: string
          description: Environment to deploy
          enum:
            - development
            - staging
            - production
        region:
          title: AWS Region
          type: string
          description: AWS Regional restriction for the bucket
          enum:
            - eu-west-1
            - eu-west-2
            - eu-central-1
        description:
          title: Description
          type: string
          description: Help others understand what this bucket is for.
        dryRun:
          title: Only perform a dry run, don't publish anything
          type: boolean
          default: false
  steps:
    - id: fetch-template
      name: Fetch AWS S3 Templates
      action: fetch:template
      if: ${{ parameters.dryRun == false }}
      input:
        targetPath: ./s3
        url: ../skeleton/crossplane/s3
        values:
          project: ${{ parameters.project }}
          app: ${{ parameters.app }}
          environment: ${{ parameters.environment }}
          region: ${{ parameters.region }}

    - id: open-pr
      name: "Open PR in GitOps Repository"
      action: publish:github:pull-request
      if: ${{ parameters.dryRun == false }}
      input:
        repoUrl: github.com?repo=backstage&owner=GMSOPS # github.com?repo=${{parameters.project}}-infrastructure&owner=${{parameters.gitOwner}}
        branchName: feat/create-${{ parameters.project }}-${{ parameters.app }}-${{ parameters.environment }}-s3
        title: ':robot: [backstage-bot] Create ${{ parameters.project }} ${{ parameters.app }} ${{ parameters.environment }} s3 bucket'
        description: |
          ${{ parameters.description if parameters.description }}
        sourcePath: s3
        targetPath: ./

    # - id: register
    #   name: Register Application in Catalog
    #   action: catalog:register
    #   if: ${{ parameters.dryRun !== true }}
    #   input:
    #     repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #     catalogInfoPath: "/catalog-info.yaml"


    - name: Results
      if: ${{ parameters.dryRun }}
      action: debug:log
      input:
        listWorkspace: true

  output:
    links:
      - title: Go to GitOps Pull Request
        url: ${{ steps.open-pr.output.remoteUrl }}
      # - title: Open in catalog
      #   icon: catalog
      #   entityRef: ${{ steps.register.output.entityRef }}