apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cf-dns-template
  title: Cloudflare DNS
  description: Create a DNS record in cloudflare

  tags:
    - dns
    - cloudflare
    - service
    - component
spec:
  owner: group:sre-team
  type: component
  parameters:
    - title: Provide some simple information
      required:
        - owner
        - type
        - ttl
        - domain
        - record
        - value
      properties:
        type:
          title: Record Type
          type: string
          description: Type of the DNS record (A,TXT,...)
          enum:
            - A
            - CNAME
            - MX
            - PTR
            - TXT
        record:
          title: DNS Record Name
          type: string
          description: DNS Record name without domain
          ui:field: EntityNamePicker
        ttl:
          title: TTL
          type: number
          description: Time-to-live of the dns record
        domain:
          title: App domain name
          type: string
          description: Unique name of the project
          enum:
            - gms-ops.net
            - iot.in.rs
        value:
          title: DNS Record Value
          type: string
          description: Value of the DNS Record
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKind:
              - Users
              - Groups
  steps:

    - action: http:backstage:request
      id: getdnszone
      name: Get DNS Zone info
      input:
        method: GET
        path: "/api/proxy/cloudflare/api/zones"
        params:
            name: ${{ parameters.domain }}

    - id: log-message
      name: Log Message
      action: debug:log
      input:
        # extra: ${{ steps.get-dns-zone.output.body }}
        message: {{ steps.getdnszone.output.code }}

    # - action: http:backstage:request
    #   id: creatednsrecord
    #   if: ${{ steps.getdnszone.output.success == true }}
    #   name: Create DNS record
    #   input:
    #     method: POST # result[0].id
    #     path: "/api/proxy/cloudflare/api/zones/${{ steps.getdnszone.output.body.result[0].id }}/dns_records"
    #     body:
    #       type: ${{ parameters.type }}
    #       name: ${{ parameters.record }}
    #       content: ${{ parameters.value }}
    #       ttl: ${{ parameters.ttl }}


    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #     #catalogInfoPath: "/catalog-info.yaml"
    #     optional: false

  output:
    links:
      - title: "{{steps.getdnszone.output.body}}"
        url: ""
      - title: "{{steps.getdnszone.output.code}}"
        url: ""
