apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nestjs-template
  title: NestJS Application
  description: Create a NestJS Application

  tags:
    - node
    - nestjs
    - recommended
    - service
    - component
spec:
  owner: group:sre-team
  type: component
  parameters:
    - title: Provide some simple information
      required:
        - owner
        - app
        - port
        - domain
        - gitOwner
      properties:
        gitOwner:
          title: Github User/Organization
          type: string
          description: Github username or organization name
          enum:
            - GMSOPS
        project:
          title: Project Name
          type: string
          description: Unique name of the project
          enum:
            - demo
        app:
          title: Application Name
          type: string
          description: Unique name of the application
          ui:field: EntityNamePicker
        port:
          title: Port
          type: number
          description: The port app listens on
        domain:
          title: App domain name
          type: string
          description: Unique name of the project
          enum:
            - gms-ops.net
        autoDns:
          title: Automatically add dns records
          type: boolean
          default: true
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKind:
              - Users
              - Groups
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ../skeleton/nest-app
        targetPath: ./app
        values:
          app: ${{ parameters.app }}
          port: ${{ parameters.port }}
          registry: harbor.mgmt.neotechsolutions.org

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        sourcePath: ./app
        description: This is ${{ parameters.app }}
        repoUrl: github.com?owner=${{ parameters.gitOwner }}&repo=${{ parameters.app }}
        defaultBranch: main


    - id: fetch_template_app
      name: Fetch Application Crossplane Templates
      action: fetch:template
      input:
        targetPath: ./app
        url: ../skeleton/crossplane/app
        values:
          project: ${{ parameters.project }}
          app: ${{ parameters.app }}
          port: ${{ parameters.port }}
          registry: harbor.mgmt.neotechsolutions.org
          hostDevelopment: ${{ parameters.app }}-${{ parameters.project }}.dev.${{ parameters.domain }}
          hostStaging: ${{ parameters.app }}-${{ parameters.project }}.stg.${{ parameters.domain }}
          hostProduction: ${{ parameters.app }}-${{ parameters.project }}.${{ parameters.domain }}

    - id: open-pr
      name: "Open PR in GitOps Repository for the app crossplanes"
      action: publish:github:pull-request
      if: ${{ parameters.dryRun == false }}
      input:
        repoUrl: github.com?repo=${{ parameters.project }}-infrastructure&owner=${{ parameters.gitOwner }}
        branchName: feat/create-${{ parameters.project }}-${{ parameters.app }}-${{ parameters.environment }}
        title: ':robot: [backstage-bot] Create ${{ parameters.project }} ${{ parameters.app }} ${{ parameters.environment }} application'
        description: |
          ${{ parameters.description if parameters.description }}
        sourcePath: app
        targetPath: ./

    - action: http:backstage:request
      id: add_dns_records
      if: ${{ parameters.autoDns }}
      name: Create DNS record
      input:
        method: POST
        path: /api/proxy/cloudflare/api/zones/1aeb1365d8a34e09be23964e9db07535/dns_records
        headers:
            'content-type': 'application/json'
        body:
          type: A
          name: ${{ parameters.app }}-${{ parameters.project }}.dev
          content: "10.0.0.1"
          ttl: 1

    - action: http:backstage:request
      id: run-workflow
      name: Run bootstrap workflow
      input:
        method: POST
        path: "/api/proxy/workflow/webhook/app-bootstrap"
        body:
          project: ${{ parameters.project }}
          app: ${{ parameters.app }}
          registry: harbor.mgmt.neotechsolutions.org
          repo: ${{ steps.publish.output.remoteUrl | slice(-4) }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        #catalogInfoPath: "/catalog-info.yaml"
        optional: false

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl | slice(-4) }}
      - title: Infrastructure Repository
        url: https://github.com/${{ parameters.gitOwner }}/${{ parameters.project }}-infrastructure
      - title: Development link
        url: ${{ parameters.app }}-${{ parameters.project }}.dev.${{ parameters.domain }}
      - title: Staging link
        url: ${{ parameters.app }}-${{ parameters.project }}.stg.${{ parameters.domain }}
      - title: Production link
        url: ${{ parameters.app }}-${{ parameters.project }}.${{ parameters.domain }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
