apiVersion: storage.gmsops.io/v1alpha1
kind: XBucket
metadata:
  name: ${{values.app}}
spec:
  compositionRef:
    name: bucket-composition
  parameters:
    project: ${{values.project}}
    app: ${{values.app}}
    environment: ${{values.environment}}
    region: ${{values.region}}

