---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: lab-dev-s3
  namespace: lab
  labels:
    backstage.io/kubernetes-id: lab
spec:
  forProvider:
    acl: private
    locationConstraint: us-east-1
    objectLockEnabledForBucket: false
  providerConfigRef:
    name: default