apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.project}}-component
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: GMSOPS/${{values.project}}-infrastructure
    backstage.io/kubernetes-namespace: backstage
spec:
  type: service
  lifecycle: production
  owner: devops
  system: demo
